import {
    mdiBookOpenPageVariant,
    mdiSchool,
    mdiFilm,
    mdiMusicNoteEighth,
    mdiTheater,
    mdiTelevision,
    mdiControllerClassic,
    mdiCrowd,
    mdiNaturePeople,
    mdiDesktopClassic,
    mdiMathCos,
    mdiUfo,
    mdiBasketball,
    mdiEarth,
    mdiHistory,
    mdiGreenhouse,
    mdiBrush,
    mdiAccountStar,
    mdiPaw,
    mdiIdeogramCjk,
    mdiCarEstate,
    mdiRedhat,
    mdiHammerScrewdriver,
    mdiPanda,
} from "@mdi/js";

export let Categories = [
    { name: "General Knowledge", id: "9", icone: mdiSchool },
    { name: "Books", id: "10", icone: mdiBookOpenPageVariant },
    { name: "Film", id: "11", icone: mdiFilm },
    { name: "Music", id: "12", icone: mdiMusicNoteEighth },
    { name: "Theatres", id: "13", icone: mdiTheater },
    { name: "Television", id: "14", icone: mdiTelevision },
    { name: "Video Games", id: "15", icone: mdiControllerClassic },
    { name: "Board Games", id: "16", icone: mdiCrowd },
    { name: "Science & Nature", id: "17", icone: mdiNaturePeople },
    { name: "Computers", id: "18", icone: mdiDesktopClassic },
    { name: "Mathematic", id: "19", icone: mdiMathCos },
    { name: "Mythology", id: "20", icone: mdiUfo },
    { name: "Sports", id: "21", icone: mdiBasketball },
    { name: "Geography", id: "22", icone: mdiEarth },
    { name: "History", id: "23", icone: mdiHistory },
    { name: "Politics", id: "24", icone: mdiGreenhouse },
    { name: "Art", id: "25", icone: mdiBrush },
    { name: "Celebrities", id: "26", icone: mdiAccountStar },
    { name: "Animals", id: "27", icone: mdiPaw },
    { name: "Japanese Anime & Manga", id: "31", icone: mdiIdeogramCjk },
    { name: "Vehicles", id: "28", icone: mdiCarEstate },
    { name: "Comics", id: "29", icone: mdiRedhat },
    { name: "Gadgets", id: "30", icone: mdiHammerScrewdriver },
    { name: "Cartoon", id: "32", icone: mdiPanda },
];


